config/routes.rb
Kiji::Application.routes.draw do
  root 'home#index'
  get 'about', to: 'home#about'
  get 'all', to: 'home#all'
  get 'month', to: 'home#month'
  get 'week', to: 'home#week'
  get 'yesterday', to: 'home#yesterday'
  
  resources :contacts, only: [:new, :create]

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title, :url, :source, :body
  validates :title, length: {:maximum => 255}
	
  self.per_page = 50

  searchable do
    text :title, :body
  end
end

app/models/contact.rb
class Contact
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :name, :email, :message
  
  validates_presence_of :email, :message
  validates_format_of :email, :with => /\A([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})\z/i
  validates_length_of :message, :maximum => 1000
  
  def initialize(attributes = {})
    attributes.each { |name, value| send("#{name}=", value) }
  end
  
  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    if @contact.valid?
      ContactMailer.contact_form(name: @contact.name, email: @contact.email, message: @contact.message).deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
    if params[:search].present?
      @searched = Article.search do
        fulltext params[:search] do 
          fields(:title, :body)
        end
        paginate(:page => params[:page] || 1)
      end
    else
      @searched = nil
    end
    
    today_range = Time.zone.now.beginning_of_day.utc..Time.zone.now.end_of_day.utc
    yesterday_range = 1.day.ago.beginning_of_day.utc..1.day.ago.end_of_day.utc
    @today_articles = Article.where(:created_at => today_range)
    @yesterday_articles = Article.where(:created_at => yesterday_range)
    
    @today_articles = @today_articles.empty? ? @yesterday_articles : @today_articles
    
    #@top_three = @today_articles.order('val DESC').limit(3).to_a
    #@today_articles = @today_articles.where.not(id: [@top_three[0].id,
    #            @top_three[1].id, @top_three[2].id])
    #            .order("#{sort_column} #{sort_direction}")
    #            .paginate(page: params[:page], :per_page => 10)
    @today_articles = @today_articles.order("#{sort_column} #{sort_direction}")
                      .paginate(page: params[:page], :per_page => result_num)
  end
  
  def yesterday
    range = 1.day.ago.beginning_of_day.utc..1.day.ago.end_of_day.utc
    @yesterday_articles = get_articles_within(range)
  end
  
  def week
    range = 1.week.ago.beginning_of_day.utc..Time.zone.now.utc
    @week_articles = get_articles_within(range)
  end
  
  def month
    range = 1.month.ago.beginning_of_day.utc..Time.zone.now.utc
    @month_articles = get_articles_within(range)
  end
  
  def all
    @all_articles = Article.all.order('val DESC')
                .order("#{sort_column} #{sort_direction}")
                .paginate(page: params[:page], :per_page => result_num)
  end
  
  def about
  end
  
  private
  
  def result_num
    25
  end
  
  def sort_column
    %w(val title source).include?(params[:sort]) ? params[:sort] : 'val'
  end
  
  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'desc'
  end
  
  def get_articles_within(range)
    Article.where(:created_at => range)
    .order("#{sort_column} #{sort_direction}")
    .paginate(page: params[:page], :per_page => result_num)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    content_for(:title) { (parts << 'Kiji').join(' - ') } unless parts.empty?
  end
  
  def sortable(column, title=nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, {:sort => column, :direction => direction}
  end
  
  def footer_date
    Time.now.year == 2014 ? "2014" : "2014-#{Time.now.year}"
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/common/_errors.html.erb
<%# Pass in the obj to this partial with :obj => @myvar %>
<% if obj.errors.any? %>
	<%= obj.errors.full_messages.each { |message| message } %>
<% end %>

app/views/common/_footer.html.erb
<div class="footer">
	<div class="row">
		<div class="medium-6 large-6 columns">
			<p>© <%= "#{footer_date} #{t('title')}" %>. All Rights Reserved.</p>
		</div>
		<div class="medium-6 large-6 columns">
			<ul class="right">
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to 'Contact', new_contact_path %></li>
			</ul>
		</div>
	</div><!-- end row -->
</div><!-- end footer -->

app/views/common/_masthead.html.erb
<div id="masthead">
	<div>
		<p><%= content_tag :strong, Time.zone.now.strftime("%A") %> <%= Time.zone.now.strftime("%B %e, %Y") %></p>
		<%= image_tag("Kiji_logo.png", :width => 100) %>
		<%= image_tag("Samurai.png", :width => 200, :class => "right") %>
	</div>
	<h1><%= t 'title' %> <small>Read the news. <%= render 'home/about' %></small></h1>
</div>

app/views/common/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <div data-alert class="alert-box radius <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
    <%= content_tag :div, msg %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/common/_search_box.html.erb
<%= form_tag(root_path, :method => "get", id: "search-form") do %>
	<%= text_field_tag :search, params[:search] %>
<% end %>

app/views/common/_topbar.html.erb
	<div class="contain-to-grid">
	<nav class="top-bar" data-topbar>
		<ul class="title-area">
			<li class="name">
				<h1><%= link_to t('title'), root_path %></h1>
			</li>
			<li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
		</ul>
		<section class="top-bar-section">
		<!-- Right Nav Section -->
			<ul class="right">
				<!-- ><li class="active"><a href="#">Right Button Active</a></li> -->
				<li class="has-dropdown"> <a href="#">Right Button with Dropdown</a>
					<ul class="dropdown">
						<li><a href="#">First link in dropdown</a></li>
					</ul>
				</li>
			</ul>
		<!-- Left Nav Section 
		<ul class="left">
			<li><a href="#">Left Nav Button</a></li>
		</ul>
		-->
		</section>
	</nav>
</div>

app/views/contacts/create.html.erb
<% title t('.title') %>
<br />
<%= render 'common/messages' %>

app/views/contacts/new.html.erb
<% title t('.title') %>
<div class="row">
  <div class="large-6 medium-6 columns">
  	<%= render 'common/messages' %>
  	<%= render 'common/errors', :obj => @contact %>
  	
  	<%= form_for @contact do |f| %>
  		<p>
		    <%= f.label :name %><br>
		    <%= f.text_field :name %>
		  </p>
		  <p>
		    <%= f.label :email %><br>
		    <%= f.text_field :email %>
		  </p>
		  <p>
		    <%= f.label :message %><br>
		    <%= f.text_area :message, :rows => "10" %>
		  </p>
		  <p>
		  	<%= f.submit "Send", :class => "button radius" %>
			</p>
		<% end %>
  </div>
  <div class="large-6 medium-6 columns">
  </div>
</div>

app/views/home/_about.html.erb
<a href="#" data-reveal-id="myModal" data-reveal>Democratically.</a>

<div id="myModal" class="reveal-modal" data-reveal>
	<h2>What is <%= t 'title' %>?</h2>
	<p class="lead">Here at <%= t 'title' %>, we like to read the news. But we feel
		there's just too much of it nowadays.
	</p>
	<p>We thought we'd come up with a clever way of making this experience less
		painful by leveraging social media. Every day, our algorithms make use of
		services such as Facebook and Twitter to sift through the most trending news.
		Our ranking is politically agnostic and entirely determined by you,
		the readers.
	</p>
	<p>
		We realize that popular news sources have a larger readership.
		But worry not! We account for this difference to give the less popular
		sources a fair chance at being heard.
	</p>
	<p>
		The more social you are, the better our top suggestions will be.
		We believe in your likes and dislikes.
		We believe in independent thinking.
		We believe in democratic reading.
	</p> 
	<p>
		Enjoy your stay!
	</p>
	<a class="close-reveal-modal">&#215;</a>
</div>

app/views/home/_article_list.html.erb
<ol class="rounded-list">
	<!-- Nesting is also possible here:
	<ol>
		<li><a href="">List sub item</a></li>
		<li><a href="">List sub item</a></li>
		<li><a href="">List sub item</a></li>
	</ol>
	-->
	<% articles.each do |article| %>
	<li>
		<div class="enumerate">
			<%= link_to article.title, article.url, :target => "_blank" %>
			<span>
				<%= fa_icon('facebook-square') %> <%= article.likes %>
				<%= fa_icon('twitter-square') %> <%= article.tweets %>
			</span>
			<%= content_tag(:span, article.source) %>
		</div>
		<div class="bounce-summary">
			<%= fa_icon('eye') %> Summary:<br />
			<%= article.body %>
		</div>
	</li>
	<% end %>
</ol>

app/views/home/_buttons.html.erb
<ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-5">
	<li><%= link_to "Today's", root_path, class: "button tiny radius" %></li>
	<li><%= link_to "Yesterday's", yesterday_path, class: "button tiny radius" %></li>
	<li><%= link_to "This Weeks's", week_path, class: "button tiny radius" %></li>
	<li><%= link_to "This Month's", month_path, class: "button tiny radius" %></li>
	<li><%= link_to "All articles", all_path, class: "button tiny radius" %></li>
</ul>

app/views/home/_search_results.html.erb
<h2>Search results:</h2>
<% @searched.results.each do |result| %>
	<%= link_to "#{result.title}", result.url, :target => "_blank" %><br />
<% end %>
<br />
<%= will_paginate @searched.results, renderer: FoundationPagination::Rails %>

app/views/home/_top_three.html.erb
<div class="row">
	<div class="large-8 medium-11 small-11">
	<ol class="circle-list">
	<% @top_three.each_with_index do |article, i| %>
		<li>
			<h3><%= link_to article.title, article.url, :target => "_blank" %></h3>
		  	<%# article.body.present? ? article.body : 'No body' %>
		  	<%= image_tag "screenshots/screenshot-#{i}.png", :width => 200, :class => "th radius" %>
		</li>
	<% end %>            
	</ol>
	</div>
</div>

app/views/home/about.html.erb
<% title 'About' %>
<p>
	Kiji started in the valleys of a faraway land, amidst a war between the gods
	of Faragon and the demons of Kriit.
</p>
<p>
	I jest, dear readers. Kiji started in a small room in London. But before that,
	it emerged from a desire to make sense of today's information overload. What better
	way to know which articles are worth reading than by <strong>ranking them democratically</strong>?
	<br />By leveraging social media, we're confident we've found a way to achieve this!
</p>
<p>
	It's lovely to see that an article has 10 likes, or that another has 1.5k likes.
	Yet this provides us readers with ZERO frame of reference as to how that stands 
	compared to other articles.
	Is it a good article? Is it a bad one? Who knows.
	What's more, these numbers provide us with ZERO reference as to how that performs 
	with respect
	to other online news sources.
</p>
<p>
	Kiji is a response to this mess. <strong>Kiji is a platform that cleans up 
	today's information overload.</strong>
</p>
<p>
	Every day, we gather data from multiple news sources and present them to you in a coherent
	way - not merely by how many likes or shares an article may have, but also by how that
	compares to other articles from different news sources. What's more, we try to bring you a brief
	summary of the top articles in case you're wondering if it's worth your time.
</p>
<p>
	This is a democratic form of reading. Not only are you helping your peers access good content
	every time you share something, it also helps lesser known news sources get a fair
	chance at being heard. Our algorithms let these democratically selected articles bubble to
	the top.
</p>
<p>
	Oh, and in case you're wondering, we don't track you in any way.
</p>
<p>
	Well, now that introductions are out of the way, <%= link_to "happy reading", root_path %>!
</p>

app/views/home/all.html.erb
<% title "All articles" %>

<%= render 'article_list', :articles => @all_articles %>
<%= will_paginate @all_articles, renderer: FoundationPagination::Rails %>

<hr />
<%= render 'buttons' %>

app/views/home/index.html.erb
<% title 'Home' %>

<%= render 'common/search_box' %>

<ul class="featurettes hide-for-small hide-for-medium">
	<li>
		<a href="">Smashing Magazine redesigns</a>
		and launches their brand new network of blogs, the Smashing Network.
	</li>
	<li>
		<a href="">Smashing Magazine redesigns</a>
		and launches their brand new network of blogs, the Smashing Network.
	</li>
	<li>
		<a href="">Smashing Magazine redesigns</a>
		and launches their brand new network of blogs, the Smashing Network.
	</li>
	<li>
		<a href="">Smashing Magazine redesigns</a>
		and launches their brand new network of blogs, the Smashing Network.
	</li>
</ul>

<%# render 'top_three' unless @searched %>

<div class="row">
	<div class="medium-12 large-12 columns">
		<% if @searched %>
			<%= render 'search_results' %>
		<% else %>
		<p class="text-center">
			Sort by:
			<%= sortable('val', 'Value') %> <%= fa_icon('sort-numeric-desc') %>
			<%= sortable('title') %> <%= fa_icon('sort-alpha-asc') %>
			<%= sortable('source') %> <%= fa_icon('sort-amount-asc') %>
		</p>
			<%= render('article_list', :articles => @today_articles) %>
			<%= will_paginate @today_articles, renderer: FoundationPagination::Rails %>
			<%= render 'buttons' %>
		<% end %>		
	</div>
	<!--<div class="medium-4 large-4 columns">
		<div class="panel">
			<h5>This is a regular panel.</h5>
			<p>It has an easy to override visual style, and is appropriately subdued.</p>
		</div>
	</div>
	-->
</div>

app/views/home/month.html.erb
<% title "This month's top articles" %>

<%= render 'article_list', :articles => @month_articles %>
<%= will_paginate @month_articles, renderer: FoundationPagination::Rails %>

<hr />
<%= render 'buttons' %>

app/views/home/week.html.erb
<% title "This week's top articles" %>

<%= render 'article_list', :articles => @week_articles %>
<%= will_paginate @week_articles, renderer: FoundationPagination::Rails %>

<hr />
<%= render 'buttons' %>

app/views/home/yesterday.html.erb
<% title "Yesterday's top articles" %>

<%= render 'article_list', :articles => @yesterday_articles %>
<%= will_paginate @yesterday_articles, renderer: FoundationPagination::Rails %>

<hr />
<%= render 'buttons' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : t('title') %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<%= render 'common/topbar' %>
  	<br />
  	<div class="row">
  		<div class="large-12 columns">
  			<%= render 'common/masthead' %>
		    <%= yield %>
		    <%= javascript_include_tag "application" %>
		</div>
	</div>
	<%= render 'common/footer' %>
  </body>
</html>